version: '2'

services:
  mycodecamp:
    image: mycodecamp:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5004:5004"
    environment:
      - REMOTE_DEBUGGING
