--- 
jobs: 
  build: 
    docker: 
      - 
        image: "microsoft/dotnet:sdk"
    environment: 
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps: 
      - checkout
      - 
        run: "echo \"hello world\""
    working_directory: /temp
version: 2
