version: 2
jobs:
   build:
     docker:
       - image: microsoft/aspnetcore-build
     environment:
       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
       DOTNET_CLI_TELEMETRY_OPTOUT: 1
     steps:
       - checkout
       - run: echo "hello world"
       - run: dotnet restore
       - run: dotnet build
