version: 2
jobs:
  build:
     docker:
       - image: microsoft/aspnetcore-build
     environment:
       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
       DOTNET_CLI_TELEMETRY_OPTOUT: 1
     steps:
       - checkout
       - run: echo "hello world"
       - run: dotnet restore
       - run: dotnet build
      deployment:
        production:
          branch: master
            commands:
               - git remote add production dokku@138.197.138.253:MyCodeCamp
               - git push production master
